### openwisp2
## tasks
- include: apt.yml
  tags: [openwisp2, apt]
  when: ansible_os_family == 'Debian'

- include: yum_centos.yml
  tags: [openwisp2, yum]
  when: ansible_os_family == 'RedHat'

- include: pip.yml
  tags: [openwisp2, pip]

- name: Set www user (Debian)
  set_fact:
    www_group: 'www-data'
    www_user:  'www-data'
  when: ansible_os_family == 'Debian'

- name: Set www user (RedHat)
  set_fact:
    www_group: 'nginx'
    www_user:  'nginx'
  when: ansible_os_family == 'RedHat'

# comprises django_secret_key.yml
- include: django.yml
  tags: [openwisp2, django]

- include: firewalld_centos.yml
  tags: [openwisp2, firewalld]
  when: ansible_os_family == 'RedHat'

- include: selinux_centos.yml
  tags: [openwisp2, selinux]
  when: ansible_os_family == 'RedHat'

- include: supervisor.yml
  tags: [openwisp2, supervisor]

- include: nginx.yml
  tags: [openwisp2, nginx]
