### openwisp2
## tasks
- include: variables.yml
  tags: [openwisp2, variables]
  
- include: apt.yml
  tags: [openwisp2, apt]
  when: ansible_os_family == 'Debian'

- include: yum.yml
  tags: [openwisp2, yum]
  when: ansible_os_family == 'RedHat'

- include: pip.yml
  tags: [openwisp2, pip]

# comprises django_secret_key.yml
- include: django.yml
  tags: [openwisp2, django]

- include: firewalld.yml
  tags: [openwisp2, firewalld]
  when: ansible_os_family == 'RedHat'

- include: selinux.yml
  tags: [openwisp2, selinux]
  when: ansible_os_family == 'RedHat'

- include: supervisor.yml
  tags: [openwisp2, supervisor]

- include: nginx.yml
  tags: [openwisp2, nginx]
