- name: create "{{ openwisp2_path }}/public_html"
  file:
    path: "{{ openwisp2_path }}/public_html"
    state: directory

- name: create "{{ openwisp2_path }}/ssl"
  file:
    path: "{{ openwisp2_path }}/ssl"
    state: directory

- name: create SSL cert if not exists yet
  command: >
    openssl req -new -nodes -x509 -subj "/C={{ openwisp2_ssl_country }}/ST={{ openwisp2_ssl_state }}/L={{ openwisp2_ssl_locality }}/O={{ openwisp2_ssl_organization }}/CN={{ openwisp2_ssl_common_name }}" -days 3650 -keyout {{ openwisp2_ssl_key }} -out {{ openwisp2_ssl_cert }} -extensions v3_ca creates={{ openwisp2_ssl_cert }}
  notify: restart nginx

- name: nginx site available
  template:
    src: ../templates/nginx.j2
    dest: "/etc/nginx/sites-available/{{ inventory_hostname }}"
  notify: restart nginx
  when: ansible_os_family == 'Debian'

- name: nginx site enabled
  file:
    src: "/etc/nginx/sites-available/{{ inventory_hostname }}"
    dest: "/etc/nginx/sites-enabled/{{ inventory_hostname }}"
    state: link
  notify: restart nginx
  when: ansible_os_family == 'Debian'

- name: nginx site
  template:
    src: ../templates/nginx.j2
    dest: "/etc/nginx/conf.d/{{ inventory_hostname }}.conf"
  notify: restart nginx
  when: ansible_os_family == 'RedHat'
