- name: uwsgi.ini
  template:
    src: ../templates/uwsgi.ini.j2
    dest: "{{ openwisp2_path }}/uwsgi.ini"
  tags:
    - openwisp2
    - supervisor

- name: supervisor uwsgi
  action: template src=../templates/supervisor.j2 dest={{ uwsgi_path }}
  notify: reload supervisor
  tags:
    - openwisp2
    - supervisor
