- name: Set uwsgi path (Debian)
  set_fact:
    uwsgi_path: '/etc/supervisor/conf.d/openwisp2.conf'
  when: ansible_os_family == 'Debian'

- name: Set uwsgi path (RedHat)
  set_fact:
    uwsgi_path: '/etc/supervisord.d/openwisp2.ini'
  when: ansible_os_family == 'RedHat'

- name: Set www user (Debian)
  set_fact:
    www_group: 'www-data'
    www_user:  'www-data'
  when: ansible_os_family == 'Debian'

- name: Set www user (RedHat)
  set_fact:
    www_group: 'nginx'
    www_user:  'nginx'
  when: ansible_os_family == 'RedHat'
