- name: Update packages
  yum:
    update_cache=yes state=latest
    name="*"

- name: Install additional repositories
  yum: name={{ item }} state=latest
  notify: reload systemd
  with_items:
    - epel-release

- name: Install system packages
  yum: name={{ item }} state=latest
  notify: reload systemd
  with_items:
    - sudo
    - gcc
    - sqlite
    - supervisor
    - nginx
    - openssl
    - openssl-devel
    - libffi-devel
    - python-devel
    - libsemanage-python

- name: ensure supervisor is started
  service: name=supervisord state=started

- name: Install python2 packages
  when: openwisp2_python in ["python2.7", "python2"]
  yum: name={{ item }} state=latest
  with_items:
    - python2-pip
    - python-devel

- name: Install python3 packages
  when: openwisp2_python == "python3"
  yum: name={{ item }} state=latest
  with_items:
    - python34
    - python34-pip
    - python34-devel

- name: Link pip from python3 to /usr/bin/pip
  when: openwisp2_python == "python3"
  file:
    src: /usr/bin/pip3
    dest: /usr/bin/pip
    state: link

- name: Install python wheel (optional, allowed to fail)
  ignore_errors: yes
  yum: name={{ item }} state=latest
  with_items:
    - python-wheel

- name: Remove system buggy virtualenv
  yum: name={{ item }} state=absent
  with_items:
    - python-virtualenv
