- name: Update YUM package cache
  yum:
    update_cache=yes state=latest
    name="*"

- name: Install additional repositories
  yum: name={{ item }} state=latest
  notify: reload systemd
  with_items:
    - epel-release
    - centos-release-scl
    - centos-release-scl-rh

- name: Install system packages
  yum: name={{ item }} state=latest
  notify: reload systemd
  with_items:
    - sudo
    - gcc
    - sqlite
    - supervisor
    - nginx
    - openssl
    - openssl-devel
    - libffi-devel
    - python-devel

# fixes issue described in https://docs.ansible.com/ansible/become.html#becoming-an-unprivileged-user
- name: Install acl if acting as non-root user
  yum: name=acl state=latest
  when: ansible_user is not defined or ansible_user != 'root'

- name: ensure supervisor is started
  service: name=supervisord state=started

- name: Install python2 packages
  when: openwisp2_python in ["python2.7", "python2"]
  yum: name={{ item }} state=latest
  with_items:
    - python-pip
    - python-dev
    - python-virtualenv

- name: Install python3 packages
  when: openwisp2_python == "python3"
  yum: name={{ item }} state=latest
  with_items:
    - python34
    - python34-pip
    - python34-devel
    - python-virtualenv

- name: Install python wheel (optional, allowed to fail)
  ignore_errors: yes
  yum: name={{ item }} state=latest
  with_items:
    - python-wheel
    # no such package in CentOS7
    # - python34-wheel

# no such package in CentOS7
#- name: Install python3-virtualenv
#  ignore_errors: yes
#  yum: name={{ item }} state=latest
#  with_items:
#    - python34-virtualenv
